# Generated by Django 4.2.5 on 2023-10-03 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='room_ID')),
                ('room_name', models.CharField(max_length=25, verbose_name='room_name')),
                ('room_created_on', models.DateTimeField(auto_now_add=True, verbose_name='room_created_on')),
                ('room_slug', models.SlugField(verbose_name='room_slug')),
            ],
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='room_id')),
            ],
        ),
    ]
