# Generated by Django 4.2.5 on 2023-10-20 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0005_alter_room_room_admin_alter_roommember_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommember',
            name='room_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='room_member_id'),
        ),
    ]
