# Generated by Django 4.2.5 on 2023-10-06 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='task_ID')),
                ('desciption', models.TextField(verbose_name='description')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='is_urgent')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is_completed')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_id', to=settings.AUTH_USER_MODEL, verbose_name='creator_id')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='task_room_id')),
                ('tasker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasker_id', to=settings.AUTH_USER_MODEL, verbose_name='tasker_id')),
            ],
        ),
    ]
