# Generated by Django 4.2.5 on 2023-10-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='task_ID')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='is_urgent')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is_completed')),
            ],
        ),
    ]
