# Generated by Django 4.2.5 on 2023-10-25 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_creator_id', to=settings.AUTH_USER_MODEL, verbose_name='task_creator_id'),
        ),
        migrations.AddField(
            model_name='task',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='task_room_id'),
        ),
        migrations.AddField(
            model_name='task',
            name='tasker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_tasker_id', to=settings.AUTH_USER_MODEL, verbose_name='task_creator_id'),
        ),
    ]
