# Generated by Django 4.2.5 on 2023-10-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='desciption',
            field=models.CharField(max_length=100, verbose_name='description'),
        ),
    ]
