# Generated by Django 4.2.5 on 2023-10-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_desciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='desciption',
            new_name='description',
        ),
    ]
