# Generated by Django 4.2.5 on 2023-10-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_desciption_task_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('is_completed',)},
        ),
    ]
