# Generated by Django 4.2.5 on 2023-10-13 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0003_alter_room_room_admin_alter_roommember_room_member'),
        ('tasks', '0004_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator_id', to=settings.AUTH_USER_MODEL, verbose_name='creator_id'),
        ),
        migrations.AlterField(
            model_name='task',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.room', verbose_name='task_room_id'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tasker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasker_id', to=settings.AUTH_USER_MODEL, verbose_name='tasker_id'),
        ),
    ]
