# Generated by Django 4.2.5 on 2023-10-13 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0005_alter_room_room_admin_alter_roommember_room_and_more'),
        ('tasks', '0005_alter_task_creator_alter_task_room_alter_task_tasker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_id', to=settings.AUTH_USER_MODEL, verbose_name='creator_id'),
        ),
        migrations.AlterField(
            model_name='task',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room', verbose_name='task_room_id'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tasker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasker_id', to=settings.AUTH_USER_MODEL, verbose_name='tasker_id'),
        ),
    ]
