# Generated by Django 4.2.5 on 2023-10-20 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_creator_alter_task_room_alter_task_tasker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
