# Generated by Django 4.2.5 on 2023-10-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, default='Member', max_length=50, null=True, verbose_name='Role'),
        ),
    ]
